### Create a new book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "The Four Agreements",
  "author": "Don Miguel Ruiz",
  "isbn": "9781878424310"
}

### Get all books
GET http://localhost:8080/books
Content-Type: application/json

### Get a book by ID
GET http://localhost:8080/books/1
Content-Type: application/json

### Get a book by ISBN
GET http://localhost:8080/books/9781878424310
Content-Type: application/json

### Update a book
PUT http://localhost:8080/books/1
Content-Type: application/json

{
  "title": "The Four Agreements - Updated",
  "author": "Don Miguel Ruiz"
}

### Delete a book by ID
DELETE http://localhost:8080/books/1
Content-Type: application/json

### Borrow a book
POST localhost:8080/books/9781878424310/checkout
Content-Type: application/json

### Get a book checkout status
GET localhost:8080/checkout-ledger/9781878424310
Content-Type: application/json

### Return a book
POST localhost:8080/books/9781878424310/return
Content-Type: application/json
